### ISSUE TITLE
`/read` command is missing

### ISSUE THREAD

**Issue by plakhin** [Aider-AI/aider#1739]
### Issue

[Tips page](https://aider.chat/docs/usage/tips.html) says I can provide up-to-date documentation using the `/read` command, but the command is missing.

### Version and model info

Aider v0.57.1
Main model: gpt-4o-2024-08-06 with diff edit format
Weak model: gpt-4o-mini
Git repo: ../../../.git with 205 files
Repo-map: using 1024 tokens, auto refresh

**Comment by fry69** [comment]
Thank you for filing this issue.

`/read` is an alias for `/read-only`, it got renamed in August last year (commit f9471fc). Since then it seems `/read` and `/read-only` seem to get used interchangeably, which is a bit confusing.

I have created this PR #1743 to revert this and only use `/read`, but I am not sure if @paul-gauthier will like this :)

**Comment by paul-gauthier** [comment]
Sorry, how is it confusing folks that the full command name is `/read-only` ? You can do `/read` in the chat without problems. Just trying to figure out how this is tripping people up.
