### ISSUE TITLE
Repeated Cost Addition on Interrupt (Ctrl-C) in Aider-Chat Sessions

### ISSUE THREAD

**Issue by tommypowerz** [Aider-AI/aider#1784]
### Issue

When using Aider-Chat, I noticed a bug related to session cost calculation. If I interrupt the AI processing by pressing Ctrl-C before it finishes its response, the cost of the last message is repeatedly added to the total session cost. This occurs each time I attempt to interrupt and restart the process, leading to inflated and inaccurate session costs.

Steps to Reproduce:

Start a session in Aider-Chat.
Send a message and let the AI start processing.
Interrupt the processing by pressing Ctrl-C before it finishes.
Repeat the process of interrupting and sending new messages.

Thank you for looking into this issue!

### Version and model info

Aider v0.57.1 with model o1-preview

**Comment by fry69** [comment]
Thank you for filing this issue.

Just to clarify:

The costs for the request happened the second you pressed return and send the request to the LLM. If you interrupt the processing, you only signal that you are not interested in receiving the reply, but the costs for the request and the reply will be billed. That is how LLMs work.

Due to that cost calculation might be inaccurate the second you interrupt the request, as you will not receive the reply with the actual cost, which happened. There may be a bug where aider will take the cost of the last reply instead, I will look into this, but consider all session cost data bogus the second you press `Ctrl-C`.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
