### ISSUE TITLE
Autonomous Internet Browsing

### ISSUE THREAD

**Issue by nicoan777** [Aider-AI/aider#1930]
I tried aider --browser with deepseek. 

We could manually enter a url, one by one.. 
Honestly, I don't know why this is limited this way. 

Is it possible to actually give aider fully autonomous Internet browsing?

**Comment by fry69** [comment]
Thank you for filing this issue.

This document may be helpful -> https://aider.chat/docs/usage/images-urls.html#web-pages

Also note that the GUI/browser interface of aider is very limited (partly due to the Streamlit SDK) and not being worked on actively. The main focus is on the interactive terminal front end.
