### ISSUE TITLE
Adding read-only files is not possible when in "subdir mode"

### ISSUE THREAD

**Issue by mrclrchtr** [Aider-AI/aider#1939]
### Issue

The autocompletion suggests the correct file:
<img width="782" alt="image" src="https://github.com/user-attachments/assets/f78476f5-b39b-4253-9c76-6b253c48df0c">

But I can't add it:
<img width="782" alt="image" src="https://github.com/user-attachments/assets/309cb867-2c30-4891-8799-a2e7f18e3c3a">

In root dir, it's working as expected.

### Version and model info

```
sonnet: true
cache-prompts: true
cache-keepalive-pings: 5
stream: false


subtree-only: true
auto-commits: false
dirty-commits: false
read: CONVENTIONS.md
```

**Comment by juninaba** [comment]
same here

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by mrclrchtr** [comment]
The problem is fixed, thank you very much!
