### ISSUE TITLE
How would aider bench on LiveBench?

### ISSUE THREAD

**Issue by chemcoder-2020** [Aider-AI/aider#1949]
### Issue

Anecdotal experience tells me LiveBench is the more reliable benchmark for choosing LLM than the Aider LLM Leaderboard which uses exercism, mostly because LiveBench questions are refreshed more often. For example, Qwen2.5 benches significantly higher than Deepseek2.5 on LiveBench for Coding, where Deepseek is the better one on Aider LLM Leaderboard. My experience concurs with LiveBench.

The question is how can I bench Aider against LiveBench to select the best models?

### Version and model info

Aider 0.59
chat-mode: diff

**Comment by ElviiAi** [comment]
I had the same thought, LiveBench in general seems to me the most practically accurate benchmark (i.e. using sonnet3.5 as architect and editor has been seemingly yielding better results than o1-preview as architect - o1 seems to have more of a mind of its own, using o1-mini as editor also feels like it requires more steering - but o1-preview as architect does seem to offer more interesting suggestions). I also ran into agreements with it with respect to other, non-code related tasks.

Not to mention (don't get me wrong, I understand aider benchmark source was chosen due to ease of implementation, since its contains tests) the Aider bench is quite old now with some questions dating 8 months - so they're likely part the training sets of some models, and the benchmark is starting to saturate. 

Also Qwen2.5 72b tends to think its Claude often; it might be a similar case to the conclusion the author of this repo made ([Using the efficient “diff” editing format, Deepseek helps all the Architect models except for Sonnet.](https://aider.chat/2024/09/26/architect.html)) - but with regards to Qwen2.5. Still if Qwen offers good long context comprehension (across its 130k context length) it might be a viable & cheaper alternative to Sonnet as an editor, with o1-preview as architect.

Anyway, back to your question - I guess there's two approaches:

1. Rely on the outdated Q&A LiveBench versions (those are on huggingface under livebench/coding dataset - dataset also contains links to leetcode), and then similarly to current Aider benchmark implementation create tests for the expected results, create a repo and run the benchmark.

2. Wrap Aider in OpenAI compatible API (which wraps up the generated files by AIder into a completions request response, says yes to all the file and edit requests, etc.) and run the benchmark as described here: https://github.com/LiveBench/LiveBench, with a more detailed description on setting a custom endpoint here: https://github.com/LiveBench/LiveBench/issues/29

The 2nd approach should let you use the up to date (not contaminated) LiveBench questions. And it would be in general a nice addition since quite a few benchmarks (i.e. https://github.com/princeton-nlp/SWE-bench/) can be ran by emulating an OAI API. But does it make total sense? I'm not sure - since a model benchmark and a "human in the loop" coding assistant are quite different. I think it may come down to your use case too. Since there's a world of difference between 0-shot questions, SWE-bench style questions and working on your own project. Sometimes it comes down to long context comprehension (I haven't seen how o1/o1-mini fair on RULER bench but I would hazard a guess they perform well across the 130k context) where Sonnet does quite well (even if Gemini Pro 002 and Opus are technically better there, they're not as good at coding/reasoning).

Probably the lowest hanging fruit would be to "unwrap" SWE-Bench-verified into a github repo like the current repo Aider bench - since it contains tests, and is fairly recently updated (2 months ago) and try the different model combinations there.

I would love to contribute to this, as Aider is an awesome project, but unfortunately currently do not have the time.

**Comment by chemcoder-2020** [comment]
Thank you for your detailed response! I will try to look into benchmarking Aider against SWE-Bench-verified. This could go in the backlog pile for now.
