### ISSUE TITLE
Architect: suggests to edit the files despite no reply from the API

### ISSUE THREAD

**Issue by Astlaan** [Aider-AI/aider#2140]
### Issue

![image](https://github.com/user-attachments/assets/f6a6d5c4-bb33-4422-a04e-04a6cc6373c3)

The image should be self explanatory.
I ran a debug command with `/run`. I got the output. I pressed `Y` to add the output to the prompt. Openrouter ran out of credits. It stops retrying and asks me if I want to edit the files, despite no changes being received.

### Version and model info

Aider version: 0.60.0
Python version: 3.11.7
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: Yes
OS: Windows 10 (64bit)
Git version: git version 2.44.0.windows.1

Aider v0.60.0
Main model: openrouter/anthropic/claude-3.5-sonnet:beta with architect edit format, prompt cache
Editor model: openrouter/anthropic/claude-3.5-sonnet:beta with editor-diff edit format
Weak model: openrouter/anthropic/claude-3-haiku:beta
Git repo: .git with 23 files
Repo-map: using 1024 tokens, files refresh
Added src\data_fetcher.py to the chat.
Added tests\test_data_fetcher.py to the chat.
Restored previous conversation history.

**Comment by paul-gauthier** [comment]
/
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
