### ISSUE TITLE
Uncaught FileNotFoundError in pathlib.py line 1216

### ISSUE THREAD

**Issue by quasar-pankaj** [Aider-AI/aider#2222]
Aider version: 0.61.0
Python version: 3.12.7
Platform: Linux-6.11.5-arch1-1-x86_64-with-glibc2.40
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.11.5-arch1-1 (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 587, in main
    git_root = setup_git(git_root, io)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 95, in setup_git
    elif Path.cwd() == Path.home():
         ^^^^^^^^^^
  File "pathlib.py", line 1195, in cwd
    return cls().absolute()
           ^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1216, in absolute
    cwd = os.getcwd()
          ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
