### ISSUE TITLE
Claude 3.5 Haiku Now Avalible

### ISSUE THREAD

**Issue by millerjes37** [Aider-AI/aider#2250]
### Claude 3.5 Haiku is now available through the Anthropic API, Amazon Bedrock, and GC Vertex AI. 

Given Sonnet's current dominance of the aider leader-board, upgrading the weaker model (touted by Anthropic as having the coding ability of Claude 3 Opus) may extend or augment this dominance.

Request: "aider --sonnet" be upgraded to use both of the SOTA 3.5 models (Sonnet 3.5 (10/22), and Haiku 3.5) as opposed to (Sonnet 3.5 (10/22), and Haiku 3.0)
 
See landing page for Claude 3.5 Haiku here:
https://www.anthropic.com/claude/haiku

Apologies for posing as an Issue, but could not find another on this. - JM

**Comment by 5ocworkshop** [comment]
Very interested in seeing how this performs.  I was poking around aider/models.py to see how to add it, but since the normal path is via litellm, until they update their models list, it isn't just a quick change.  As of right now, Nov. 4/24 it isn't on the list yet: https://[raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json](https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json)

**Comment by paul-gauthier** [comment]
This is on the new leaderboard and `aider --haiku` uses it in the latest release.

You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
```

If you have a chance to try it, let me know if it works better for you.
