### ISSUE TITLE
Aider isn't given me the chance to respond his questions.

### ISSUE THREAD

**Issue by fcjbispo** [Aider-AI/aider#2299]
### Issue

I wrote a CONVENTIONS.md file instructing Aider to follow some guidelines on witch I told him can ask me for any question he is in doubt, just like Cline does. But however, he is not giving me a chance to respond, just giving the default Edit Files? [Y/N] just like the print below:
![image](https://github.com/user-attachments/assets/4ed09fd3-f0cd-46ea-a377-a0277b06cf81)

Is this some misconfiguration from mine or some kind of limitation? If so, please think about adding this behaviour.

Thanks.
[CONVENTIONS.md](https://github.com/user-attachments/files/17671216/CONVENTIONS.md)

### Version and model info

Aider v0.62.1
Model: anthropic/claude-3-5-haiku-20241022 with architect edit format, prompt cache, infinite output
Editor model: anthropic/claude-3-5-haiku-20241022 with diff edit format
Git repo: .git with 36 files
Repo-map: using 1024 tokens, files refresh

**Comment by Netzvamp** [comment]
Aider hasn't a detection for questions asked by the LLM. But nothing is stopping you from just say "No" and then answer it in your next question. Aider uses the whole chat history, so the LLM knows you refer to the last question.

Alternatively you can also use the "/ask" mode, that never edits any files. 

And with "/code" mode you get the "old" behavior of just editing with every request, but i say that just for reference, since i don't use that not very often, since the architect mode produces far better results.

**Comment by fcjbispo** [comment]
Ok, thats fine. Thanks bery much.

Em sex., 8 de nov. de 2024 07:58, RL ***@***.***> escreveu:

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
