### ISSUE TITLE
skip the downloading for `model_prices_and_context_window.json`

### ISSUE THREAD

**Issue by gxm11** [Aider-AI/aider#2404]
### Issue

Hi, the program checks the TTL of `model_prices_and_context_window.json` and tries to download a new file every 24 hours. However, if the download process fails, the TTL will not be refreshed, which will cause the next aider to repeat the download process. This will slow down the startup time by 5 seconds.

I think the cache TTL should be refreshed even if the download fails. In fact, the function `get_model_from_cached_json_db` will return an empty `dict()` if an error occurs. This means that the return value is not important for later programs, especially those who are willing to enter prices or context windows manually.

Or can you provide some way to skip the downloading, such as an environment variable?

### Version and model info

Aider 0.63.2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Good suggestion.

Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by gxm11** [comment]
Thank you for your efforts, I think the current plan is good enough, and there are no other problems.
