### ISSUE TITLE
Openrouter using DeepSeek: No endpoints found for this model.'

### ISSUE THREAD

**Issue by jcald1** [Aider-AI/aider#2444]
### Issue

When using aider with deepseek, I'm getting the following error. It works in the Openrouter Web UI.

```
litellm.NotFoundError: NotFoundError: OpenrouterException - Error code: 404 - 
{'error': {'message': 'No endpoints found for this model.', 'code': 404}}

```

### Version and model info

aider 0.64.1
aider --model openrouter/deepseek/deepseek-coder
Linux Mint 21.3 Virginia

**Comment by shamanicvocalarts** [comment]
seconding this issue. your openrouter endpoints are out of date and need to be updated. the correct endpoint for the deepseek model is openrouter/deepseek/deepseek-chat. chat is the latest & best at coding model from deepseek. changing to openrouter/deepseek/deepseek-chat works fine but doesnt give token cost predicitions and defaults to sane usage. please update documentation & backend to use the correct deepseek model

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like @jcald1 ran aider with `--model openrouter/deepseek/deepseek-coder` which not the correct model name.

To use Deepseek V2.5 with OpenRouter you should do `--model openrouter/deepseek/deepseek-chat`

**Comment by shamanicvocalarts** [comment]
> Thanks for trying aider and filing this issue.
> 
> It looks like @jcald1 ran aider with `--model openrouter/deepseek/deepseek-coder` which not the correct model name.
> 
> To use Deepseek V2.5 with OpenRouter you should do `--model openrouter/deepseek/deepseek-chat`

this is correct @paul-gauthier  , however it should be noted that aiders documentation & its interactive shell tell users to use --model openrouter/deepseek/deepseek-coder so this should be corrected in aider to prevent user error

**Comment by paul-gauthier** [comment]
Sorry, can you show me where in the docs you see the incorrect model name? And can you show me how the interactive shell shows it?

**Comment by shamanicvocalarts** [comment]
![image](https://github.com/user-attachments/assets/ecb14a2f-44c6-405c-b842-af4d98f14e99)

─────────────────────────────────────────
> /models openrouter/deep                

Models which match "openrouter/deep":
- openrouter/deepseek/deepseek-coder
─────────────────────────────────────────
>  


and to be clear, it would have been more accurate of me to say in the interactive documentation, IE what aider shows you with /models or when looking through aiders code. in the actual documentation it just says any openrouter provided model& doesnt specify an incorrect deepseek address

**Comment by parkero** [comment]
This problem unfortunately still exists, screenshots at the bottom for more info. 
I would be willing to do the pull request for this after confirmation.
### Summary
- **`openrouter/deepseek/deepseek-coder`** still exists as a model, but has no endpoints
- **`openrouter/deepseek/deepseek-chat`** is available and has fully replaced coder on openrouter (if you click on `coder` on the openrouter website it redirects to `chat`)
- Solution may be as easy as changing the word 'coder' to 'chat' in the following file (since coder is no longer accessible on openrouter)
    - https://github.com/Aider-AI/aider/blob/eb9c41f2a0087e90936d55d3e4ba3c9b7be3e517/aider/models.py#L662
- otherwise a new model for openrouter/deepseek/deepseek-chat can/should be added in models.py with the appropriate settings

---

#### deepseek-coder attempt - can't use at all
<img width="660" alt="Screenshot 2024-12-22 at 2 28 32 AM" src="https://github.com/user-attachments/assets/a4399031-141f-44a0-b294-c39ef64877b0" />

---

#### deepseek-chat attempt - unknown model warning, no token price, no repomap
<img width="655" alt="Screenshot 2024-12-22 at 2 37 26 AM" src="https://github.com/user-attachments/assets/072f6ad4-f24d-4f66-864e-b7bfb7951fb8" />

**Comment by paul-gauthier** [comment]
The next version will have model settings for openrouter/deepseek/deepseek-chat.

**Comment by jcald1** [comment]
Agreed that it still exists. Using the updated model name as described
above works for me.

I think it’s better to just do a PR.

**Comment by jcald1** [comment]
Opened this PR: https://github.com/Aider-AI/aider/pull/2711

**Comment by ElonSatoshi** [comment]
New aider user here, I just came across this issue using default settings. This issue should really be reopened.

**Comment by ElonSatoshi** [comment]
Specifically I get this error for deepseek-r1:free

**Comment by euxaristia** [comment]
Just got this error too in 2026 as a new user with a fresh install (default settings).
