### ISSUE TITLE
aider-install issues (python version and existing executable)

### ISSUE THREAD

**Issue by gregid** [Aider-AI/aider#2638]
### Issue

With new aider-install on WSL2 (Ubuntu) and following 2 setups:
Python: 3.11
Aider: 65.1
and
Python: 3.9
Aider: 68.0
Upgrading to Aider 69.0 brings following errors:
```
error: Executable already exists: aider (use `--force` to overwrite)
Failed to install aider: Command '/home/gt/.local/bin/uv tool install --python python3.12 aider-chat@latest' returned non-zero exit status 2.
```
There are 2 issues:
1. Python is hardcoded to version 3.12
2. it assumes aider has not been installed

On both machines I changed the command to the following to make it work:
```cli
/home/gt/.local/bin/uv tool install --python python3 aider-chat@latest --force
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I really appreciate the feedback on this new install method.

I've added `--force` to aider-install, thanks.

The python3.12 is intentional. It will install a clean version of python3.12 if needed, so that aider is running on a known good version of python.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
